#!/usr/bin/env node
/**
 * Codex-powered Agent Executor
 * OpenAI APIを使用してMiyabiエージェントの代わりにIssueを処理
 */

import https from 'https';
import { readFileSync } from 'fs';

const ISSUE_NUMBER = process.env.ISSUE_NUMBER;
const REPOSITORY = process.env.REPOSITORY;
const GITHUB_TOKEN = process.env.GITHUB_TOKEN;
const OPENAI_API_KEY = process.env.OPENAI_API_KEY || process.env.LLM_API_KEY;
const OPENAI_ENDPOINT = process.env.OPENAI_ENDPOINT || process.env.LLM_ENDPOINT || 'https://api.openai.com/v1/chat/completions';
const OPENAI_MODEL = process.env.OPENAI_MODEL || 'gpt-4o';

async function fetchIssue(issueNumber) {
  const [owner, repo] = REPOSITORY.split('/');
  const url = `https://api.github.com/repos/${owner}/${repo}/issues/${issueNumber}`;
  
  return new Promise((resolve, reject) => {
    https.get(url, {
      headers: {
        'Authorization': `Bearer ${GITHUB_TOKEN}`,
        'Accept': 'application/vnd.github+json',
        'User-Agent': 'Codex-Agent'
      }
    }, (res) => {
      let data = '';
      res.on('data', chunk => data += chunk);
      res.on('end', () => {
        if (res.statusCode === 200) {
          resolve(JSON.parse(data));
        } else {
          reject(new Error(`GitHub API error: ${res.statusCode} ${data}`));
        }
      });
    }).on('error', reject);
  });
}

async function callOpenAI(messages) {
  return new Promise((resolve, reject) => {
    const url = new URL(OPENAI_ENDPOINT);
    const postData = JSON.stringify({
      model: OPENAI_MODEL,
      messages: messages,
      temperature: 0.7,
      max_tokens: 2000
    });

    const options = {
      hostname: url.hostname,
      port: url.port || 443,
      path: url.pathname + url.search,
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${OPENAI_API_KEY}`,
        'Content-Type': 'application/json',
        'Content-Length': Buffer.byteLength(postData)
      }
    };

    const req = https.request(options, (res) => {
      let data = '';
      res.on('data', chunk => data += chunk);
      res.on('end', () => {
        if (res.statusCode === 200) {
          const result = JSON.parse(data);
          resolve(result.choices[0].message.content);
        } else {
          reject(new Error(`OpenAI API error: ${res.statusCode} ${data}`));
        }
      });
    });

    req.on('error', reject);
    req.write(postData);
    req.end();
  });
}

async function analyzeIssue(issue) {
  const prompt = `あなたはコード生成エージェントです。以下のGitHub Issueを分析し、実装すべき内容を提案してください。

Issue #${issue.number}: ${issue.title}

${issue.body}

リポジトリ: ${REPOSITORY}

以下の形式で回答してください：
1. 問題の要約
2. 実装すべき機能
3. 変更が必要なファイル
4. 実装ステップ

JSON形式で回答してください。`;

  const response = await callOpenAI([
    { role: 'system', content: 'You are a helpful coding assistant that analyzes GitHub issues and proposes implementation plans.' },
    { role: 'user', content: prompt }
  ]);

  return response;
}

async function generateCode(analysis, issue) {
  const prompt = `以下の分析に基づいて、実装コードを生成してください。

分析結果:
${analysis}

Issue #${issue.number}: ${issue.title}

必要なファイルとコードを生成してください。`;

  const response = await callOpenAI([
    { role: 'system', content: 'You are a senior software engineer. Generate production-ready code based on the analysis.' },
    { role: 'user', content: prompt }
  ]);

  return response;
}

async function main() {
  try {
    console.log(`🚀 Starting Codex-powered agent for Issue #${ISSUE_NUMBER}`);
    
    if (!OPENAI_API_KEY) {
      throw new Error('OPENAI_API_KEY or LLM_API_KEY environment variable is required');
    }

    // Issueを取得
    console.log(`📋 Fetching Issue #${ISSUE_NUMBER}...`);
    const issue = await fetchIssue(ISSUE_NUMBER);
    console.log(`✅ Issue fetched: ${issue.title}`);

    // Issueを分析
    console.log('🔍 Analyzing issue...');
    const analysis = await analyzeIssue(issue);
    console.log('✅ Analysis complete');

    // コードを生成
    console.log('💻 Generating code...');
    const code = await generateCode(analysis, issue);
    console.log('✅ Code generation complete');

    // 結果を出力
    console.log('\n📊 Analysis Result:');
    console.log(analysis);
    console.log('\n💻 Generated Code:');
    console.log(code);

    // Issueにコメント
    const [owner, repo] = REPOSITORY.split('/');
    const commentUrl = `https://api.github.com/repos/${owner}/${repo}/issues/${ISSUE_NUMBER}/comments`;
    const commentBody = JSON.stringify({
      body: `## 🤖 Codex Agent Execution Complete

**Analysis:**
\`\`\`
${analysis}
\`\`\`

**Generated Code:**
\`\`\`
${code}
\`\`\`

*This was generated by Codex-powered agent using OpenAI API.*`
    });

    await new Promise((resolve, reject) => {
      const url = new URL(commentUrl);
      const req = https.request({
        hostname: url.hostname,
        port: 443,
        path: url.pathname,
        method: 'POST',
        headers: {
          'Authorization': `Bearer ${GITHUB_TOKEN}`,
          'Accept': 'application/vnd.github+json',
          'Content-Type': 'application/json',
          'Content-Length': Buffer.byteLength(commentBody),
          'User-Agent': 'Codex-Agent'
        }
      }, (res) => {
        let data = '';
        res.on('data', chunk => data += chunk);
        res.on('end', () => {
          if (res.statusCode >= 200 && res.statusCode < 300) {
            resolve();
          } else {
            reject(new Error(`GitHub API error: ${res.statusCode} ${data}`));
          }
        });
      });
      req.on('error', reject);
      req.write(commentBody);
      req.end();
    });

    console.log('✅ Comment added to issue');
    process.exit(0);
  } catch (error) {
    console.error('❌ Error:', error.message);
    process.exit(1);
  }
}

main();

